config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :products
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/services', to: 'static_pages#services'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/store', to: 'store#index'

  resources :users
  resources :charges, only: %i[new create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone_number, phone: true, uniqueness: { case_sensitive: false }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 256 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def downcase_email
    email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update show destroy]
  before_action :correct_user, only: %i[edit update show]
  before_action :admin_user, only: %i[index destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :phone_number)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in'
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_forms.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.text_field :name, class: 'form-control', placeholder: 'Full name', autofocus: true %>

  <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>

  <%= f.text_field :phone_number, class: 'form-control', placeholder: 'Phone Number' %>

  <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

  <%= f.password_field :password_confirmation, class: 'form-control',
                       placeholder: 'Confirm password' %>


  <%= f.submit 'Save changes', class: 'btn sbtn1' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'delete', user, method: :delete,
                  data: { confirm: 'You sure?' } %>
  <% end %>
</li>

app/views/users/_whiteheader.html.erb
<nav class="navbar navbar-inverse navbar-expand-lg bg-company-white">
  <a class="navbar-brand" href="#">
    <%= link_to image_tag('logodark.png', height: '49px', width: '138px',
                          class: 'd-inline-block align-top', alt: 'Nitkleeners',), root_path %>
    <!-- <img src="/assets/G.png" height="50px" class="d-inline-block align-top" alt="">-->
  </a>
  <button class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
    <i class="material-icons darkblue">reorder</i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Services', services_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      </li>

      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Profile', current_user, class: 'dropdown-item' %>
            <%= link_to 'Settings', edit_user_path(current_user), class: 'dropdown-item' %>
            <%= link_to 'Store', store_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <%# elsif logged_in? && current_user.admin? %>
        <!--<li class="nav-item">
          <%#= link_to 'Users', users_path, class: 'nav-link' %>
        </li>-->

      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'btn sbtn1' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<p style="padding:30px;"></p>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<%= render 'users/whiteheader' %>

<i class="material-icons md-48 darkblue" style="display: inline-block;
    width: 100%;">build</i>
<h3 style="text-align: center; color: #083944;">Update your profile</h3>
<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= render 'forms' %>
    </div>
  </div>
</div>


<%= render 'layouts/getintouch' %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<%= render 'users/whiteheader' %>
<h3 style="color: #083944; text-align: center;">All users</h3>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<%= render 'users/whiteheader' %>

<div class="container">
  <div class="col-12">
    <i class="material-icons md-48 darkblue" style="display: inline-block;
        width: 100%;">input</i>
    <h3 style="text-align: center; color: #083944;">Sign up</h3>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-12 col-md-4 offset-md-4">
      <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.text_field :name, class: 'form-control', placeholder: 'Full Name', autofocus: true %>

        <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>

        <%= f.text_field :phone_number, class: 'form-control', placeholder: 'Phone Number' %>

        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>

        <%= f.password_field :password_confirmation, class: 'form-control',
                             placeholder: 'Confirm Password' %>

        <h6 style="text-align: center; color: #083944;">By creating an account,
          you agree to our Terms of use and that you
          have read our privacy policy, Terms and Conditions and Cookie policy</h6>

        <%= f.submit 'Create Account', class: 'btn sbtn1' %>
        <p style="color: #083944;">
          Have an account? <%= link_to 'Log in', login_path, class: 'btn sbtn1' %></p>
      <% end %>
    </div>
  </div>
</div>


<%= render 'layouts/getintouch' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<%= render 'users/whiteheader' %>