config/routes.rb
Rails.application.routes.draw do

  resources :line_items
  resources :carts
  resources :products
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/services', to: 'static_pages#services'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/store', to: 'store#index'

  resources :users
  resources :charges, only: %i[new create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    # line_items.to_a.sum { |item| item.total_price }
    line_items.to_a.sum(&:total_price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to store_url
    flash[:info] = 'Your cart is currently empty'
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to user_url
    flash[:danger] = 'Invalid cart'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render 'users/whiteheader' %>

<div class="container">
  <i class="material-icons md-48 darkblue" style="display: inline-block;
      width: 100%;">add_shopping_cart</i>
  <h3 style="text-align: center; color: #083944;">Your Cart</h3>
  <p style="padding: 10px;"></p>
    <% @cart.line_items.each do |item| %>
      <div class="row">
        <div class="col-sm-3">
          <%= item.quantity %> &times;
        </div>

        <div class="col-sm-3">
          <%= item.product.title %>
        </div>

        <div class="col-sm-3 item_price">
          <%=
            number_to_currency(item.total_price, unit: "₦") %>
        </div>

        <div class="col-sm-3">
          <%= link_to 'Remove item', @line_item, method: :delete, data: { confirm: 'Are you sure? ' },
          class: 'btn btn-sm btn-danger'%>
        </div>
        <p style="padding: 2px;"></p>
      </div>
    <% end %>
  <p style="padding: 10px;"></p>
  <div class="row">
    <div class="col-sm-6"><strong>Total</strong></div>
    <div class="col-sm-3 total_cell">
      <strong><%= number_to_currency(@cart.total_price, unit: "₦") %></strong></div>
    <div class="col-sm-3"><%= link_to '<strong>Empty cart</strong>'.html_safe, @cart,
                                      method: :delete, data: {confirm: 'Are you sure?'},
                                      class: 'btn btn-sm btn-danger' %></div></div>
  </div>
  <p style="padding: 10px;"></p>
  <div class="container">
    <%= link_to 'Continue shopping', store_path, class: 'btn btn-sm sbtn1' %>
    <%= link_to 'Checkout', new_charge_path, class: 'btn btn-sm sbtn1' %>
  </div>
</div>
<p style="padding: 10px;"></p>


<%= render 'layouts/getintouch' %>